= Configure the Trustee operator

Now that the Trustee operator is installed, we need to set it up.

[#trustee-route]
== Create a route for Trustee

Create a secure route with edge TLS termination for Trustee. External ingress traffic reaches the router pods as HTTPS and passes on to the Trustee pods as HTTP.

. Create a route.
+
[source,sh,role=execute]
----
oc create route edge --service=kbs-service --port kbs-port \
  -n trustee-operator-system
----
+
NOTE: Currently, only a route with a valid CA-signed certificate is supported. You cannot use a route with self-signed certificate.

. Set the TRUSTEE_HOST variable. This variable will be useful later when we set the xref:02-configure-osc.adoc#pp-cm[peer-pods ConfigMap]
+
[source,sh,role=execute]
----
TRUSTEE_HOST=$(oc get route -n trustee-operator-system kbs-service \
  -o jsonpath={.spec.host})

echo $TRUSTEE_HOST
----
+
Example output:
+
[source,texinfo,subs="attributes"]
----
kbs-service-trustee-operator-system.apps.rs01nyk5.eastus.aroapp.io
----

[#trustee-secret]
== Create a Trustee authentication secret

. Create private and public keys.
+
[source,sh,role=execute]
----
openssl genpkey -algorithm ed25519 > trustee_privateKey
openssl pkey -in trustee_privateKey -pubout -out trustee_publicKey
----

. Create a secret with the public key.
+
[source,sh,role=execute]
----
oc create secret generic kbs-auth-public-key --from-file=trustee_publicKey -n trustee-operator-system
----

. Inspect the newly created secret.
+
[source,sh,role=execute]
----
oc get secret -n trustee-operator-system
----

[#trustee-cm]
== Create Trustee ConfigMap

Create the and apply the Trustee `kbs-configmap.yaml` ConfigMap.

[source,sh,role=execute]
----
cat > kbs-configmap.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: kbs-config-cm
  namespace: trustee-operator-system
data:
  kbs-config.json: |
    {
      "insecure_http" : true,
      "sockets": ["0.0.0.0:8080"],
      "auth_public_key": "/etc/auth-secret/publicKey",
      "attestation_token_config": {
        "attestation_token_type": "CoCo"
      },
      "repository_config": {
        "type": "LocalFs",
        "dir_path": "/opt/confidential-containers/kbs/repository"
      },
      "as_config": {
        "work_dir": "/opt/confidential-containers/attestation-service",
        "policy_engine": "opa",
        "attestation_token_broker": "Simple",
          "attestation_token_config": {
          "duration_min": 5
          },
        "rvps_config": {
          "store_type": "LocalJson",
          "store_config": {
            "file_path": "/opt/confidential-containers/rvps/reference-values/reference-values.json"
          }
         }
      },
      "policy_engine_config": {
        "policy_path": "/opt/confidential-containers/opa/policy.rego"
      }
    }
EOF

cat kbs-configmap.yaml
----

[#trustee-conf]
== Configure Trustee

You can configure the following values, policies, and secrets for Trustee:

* Resource access policy.
* Optional: Secret for container image signature verification.
* Container image signature verification policy. This policy is mandatory. If you do not use container image signature verification, you must create a policy that does not verify signatures.
* If using TDX: Provisioning Certificate Caching Service for Intel Trust Domain Extensions (TDX).
* Optional: Reference values for the Reference Value Provider Service.
* Optional: Attestation policy.
* Optional: Secret for custom keys for Trustee clients.

In the above sections, we will elencate how to set up all these options, but for the purpose of the workshop, setting up the mandatory ones is enough.


. **Provisioning Certificate Caching Service for TDX**
+
If your TEE is **Intel Trust Domain Extensions (TDX)**, you must configure the Provisioning Certificate Caching Service (PCCS). The PCCS retrieves Provisioning Certification Key (PCK) certificates and caches them in a local database.
+
[source,sh,role=execute]
----
cat > tdx-config.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: tdx-config
  namespace: trustee-operator-system
data:
  sgx_default_qcnl.conf: | \
      {
        "collateral_service": "https://api.trustedservices.intel.com/sgx/certification/v4/",
        "pccs_url": "<pccs_url>"
      }
EOF

cat tdx-config.yaml
----
+
For `pccs_url`, specify the PCCS URL, for example, `https://localhost:8081/sgx/certification/v4/`.
+
Once the `pccs_url` has been added, apply the ConfigMap.
+
[source,sh,role=execute]
----
oc apply -f tdx-config.yaml
----

. **Reference values (optional)**
+
You can configure reference values for the Reference Value Provider Service (RVPS) by specifying the trusted digests of your hardware platform.
+
The client collects measurements from the running software, the Trusted Execution Environment (TEE) hardware and firmware and it submits a quote with the claims to the Attestation Server. These measurements must match the trusted digests registered to the Trustee. This process ensures that the confidential VM (CVM) is running the expected software stack and has not been tampered with.
+
[source,sh,role=execute]
----
cat > rvps-configmap.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: rvps-reference-values
  namespace: trustee-operator-system
data:
  reference-values.json: |
    [
    ]
EOF

cat rvps-configmap.yaml
----
+
Inside `reference-values.json` field, specify the trusted digests for your hardware platform if required. Otherwise, leave it empty. For the purpose of this workshop, you can leave it empty.
+
Once the reference values have been added, apply the ConfigMap.
+
[source,sh,role=execute]
----
oc apply -f rvps-configmap.yaml
----

. **Attestation policy (optional)**
+
By default, Trustee has already an attestation policy. You can overwrite the default one by creating your own attestation policy.
+
[source,sh,role=execute]
----
cat > attestation-policy.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: attestation-policy
  namespace: trustee-operator-system
data:
  default.rego: |
     package policy
     import future.keywords.every

     default allow = false

     allow {
        every k, v in input {
            judge_field(k, v)
        }
     }

     judge_field(input_key, input_value) {
        has_key(data.reference, input_key)
        reference_value := data.reference[input_key]
        match_value(reference_value, input_value)
     }

     judge_field(input_key, input_value) {
        not has_key(data.reference, input_key)
     }

     match_value(reference_value, input_value) {
        not is_array(reference_value)
        input_value == reference_value
     }

     match_value(reference_value, input_value) {
        is_array(reference_value)
        array_include(reference_value, input_value)
     }

     array_include(reference_value_array, input_value) {
        reference_value_array == []
     }

     array_include(reference_value_array, input_value) {
        reference_value_array != []
        some i
        reference_value_array[i] == input_value
     }

     has_key(m, k) {
        _ = m[k]
     }
EOF

cat attestation-policy.yaml
----
+
NOTE: For the `package policy`, the attestation policy follows the Open Policy Agent specification. In this example, the attestation policy compares the claims provided in the attestation report to the reference values registered in the RVPS database. The attestation process is successful only if all the values match.
+
Once you defined your own policy, apply it.
+
[source,sh,role=execute]
----
oc apply -f attestation-policy.yaml
----

. **Secret for container image signature verification (optional)**
+
If you use container image signature verification, you must create a secret that contains the public container image signing key. The Trustee Operator uses the secret to verify the signature, ensuring that only trusted and authenticated container images are deployed in your environment.
+
Specify the secret `<type>` (for example `img-sig`), the secret `<tag>` (for example `pub-key`), and `<public_key_file>`, the public container image signing key.
+
[source,sh,role=execute]
----
CONTAINER_IMAGE_SIGNATURE_TYPE=<type>
CONTAINER_IMAGE_SIGNATURE_TAG=<tag>
CONTAINER_IMAGE_SIGNATURE_PK=<public_key_file>
----
+
Create a secret with the following command:
+
[source,sh,role=execute]
----
oc apply secret generic $CONTAINER_IMAGE_SIGNATURE_TYPE \
    --from-file=$CONTAINER_IMAGE_SIGNATURE_TAG=./$CONTAINER_IMAGE_SIGNATURE_PK \
    -n trustee-operator-system
----
+
Note that `CONTAINER_IMAGE_SIGNATURE_TYPE` will be later used in the xref:02-configure-trustee.adoc:#trustee-kbsconfig[KbsConfig]
