= {lab_name}

Openshift sandboxed containers support for Red Hat Openshift provides you with built-in support for running Kata Containers as an additional optional runtime. The new runtime supports containers in dedicated virtual machines (VMs), providing improved workload isolation. This is particularly useful for performing the following tasks:

* Run privileged or untrusted workloads
* Ensure isolation for sensitive workloads
* Ensure kernel isolation for each workload
* Share the same workload across tenants
* Ensure proper isolation and sandboxing for testing software
* Ensure default resource containment through VM boundaries

Please refer to https://docs.redhat.com/en/documentation/openshift_sandboxed_containers[Openshift sandboxedcontainers official documentation, window=blank] for more information.

Red Hat OpenShift sandboxed containers provides also the capability to run https://www.redhat.com/en/blog/learn-about-confidential-containers[**confidential containers (CoCo)**, window=blank]. Confidential Containers are containers deployed within an isolated hardware enclave protecting data and code from privileged users such as cloud or cluster administrators. The https://confidentialcontainers.org/[CNCF Confidential Containers project, window=blank] is the foundation for the OpenShift CoCo solution.Note that CoCo is an additional feature provided by OpenShift sandboxed containers, and consequently, it's available through the OpenShift sandboxed containers operator.

Please refer to the https://www.redhat.com/en/blog/exploring-openshift-confidential-containers-solution[Exploring the OpenShift confidential containers solution, window=blank] blogpost for more information.

We are also providing another operator, the **confidential compute attestation operator** (also known as Trustee), which can verify the trustworthiness of TEEs remotely. For more information, please refer to https://www.redhat.com/en/blog/introducing-confidential-containers-trustee-attestation-services-solution-overview-and-use-cases[this blogpost, window=blank].

This workshop will show how to set up the Trustee and OSC operator and run a simple hello-openshift **confidential container** running with the *kata-remote* runtime class (peer pods solution). This effectively means that the hello-openshift container runs in a **separate**, **confidential**, **independent** virtual machine, and not in the worker node.

The peer-pods solution extends Red Hat Openshift sandboxed containers (OSC) to run on any environment without requiring bare-metal servers or nested virtualization support. It does this by extending Kata containers runtime (which OSC is built on) to handle VM lifecycle management using cloud provider APIs (AWS, Azure, etc...) or third-party hypervisors APIs (such as VMware vSphere). More info on the peer pods solution is available https://www.redhat.com/en/blog/red-hat-openshift-sandboxed-containers-peer-pods-solution-overview[here, window=blank].

[#credentials]
== Setting up the environment

. Navigate to the console website: {aro_console}[Openshift Console, window=blank]

. Login as administrator:
* *Username:* {aro_kube_username}
* *Password:* {aro_kube_password}

. Go into the terminal on the right and run the following commands:
* Log into azure CLI: `az login --service-principal -u {azure_service_principal_id} -p {azure_service_principal_password} --tenant {azure_tenant_id}`
* Export the `AZURE_RESOURCE_GROUP` variable. It will needed when setting up the operator:
`export AZURE_RESOURCE_GROUP={azure_resource_group}`
