= {lab_name}

OpenShift sandboxed containers support for Red Hat OpenShift provides you with built-in support for running Kata Containers as an additional optional runtime. The new runtime supports containers in dedicated virtual machines (VMs), providing improved workload isolation. This is particularly useful for performing the following tasks:

* Run privileged or untrusted workloads
* Ensure kernel isolation for each workload
* Share the same workload across tenants
* Ensure proper isolation and sandboxing for testing software
* Ensure default resource containment through VM boundaries

Please refer to https://docs.redhat.com/en/documentation/openshift_sandboxed_containers[Openshift sandboxedcontainers official documentation] for more information.

This workshop will show how to set up the OSC operator and run a simple hello-world container running with the kata-remote runtime class, which is the result of the peer-pods technology offered by the operator in the cloud.

The peer-pods solution extends Red Hat OpenShift sandboxed containers (OSC) to run on any environment without requiring bare-metal servers or nested virtualization support. It does this by extending Kata containers runtime (which OSC is built on) to handle VM lifecycle management using cloud provider APIs (AWS, Azure, etc...) or third-party hypervisors APIs (such as VMware vSphere). More info on the peer pods solution is available https://www.redhat.com/en/blog/red-hat-openshift-sandboxed-containers-peer-pods-solution-overview[here].


== Setting up the environment

. Navigate to the link:{openshift_cluster_console_url}[OpenShift Console^]

. Login as administrator:
* *Username:* {openshift_cluster_admin_username}
* *Password:* {openshift_cluster_admin_password}

. Write down your Azure credentials:
* *AZURE_CLIENT_ID:*
* *AZURE_CLIENT_SECRET:*
* *AZURE_TENANT_ID:*
* *AZURE_SUBSCRIPTION_ID:*
